name: Deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: test the code
        run: npm run test
      - name: Build the code
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: files
          path: suraj
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v4
        with:
           name: files
      - name: Content of outpurt
        run: ls
            
 