name: Deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: cache
        uses: actions/cache@v4
        with: 
          path: ~./npm
          key: my-${{ hashFiles('**/package-lock.json') }}

      - name: install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: test the code
        run: npm run test
        id: mytest
      - name: Build the code
        if: success() && steps.mytest.outcome == 'success'
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: files
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: cache
        uses: actions/cache@v4
        with: 
          path: ~./npm
          key: my-${{ hashFiles('**/package-lock.json') }}
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
           name: files
      - name: Content of output
        run: ls
  share:
    runs-on: ubuntu-latest
    steps:
      - name: share the package
        run: echo "Share the Package"
    
  report:
    needs:
      - deploy
      - share
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print
        run: echo "Report"

