name: Deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
      - name: install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: test the code
        run: npm run test
      - name: Build the code
        run: npm run build
