name: Docker

on: workflow_dispatch

jobs:
    Build:
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v4
        
          - name: Setup node and dependecies
            uses: ./.github/actions

          - name: Build the code
            run: npm run build
          
          - name: Download artifacts
            uses: actions/upload-artifact@v4
            with: 
              name: myfiles
              path: build
          - name: Push artifacts to s3
            uses: ./.guthub/actions/docker
            with: 
              bucket: mybucket
              file: build
              key: test
          